services:
  - type: web
    name: electricity-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd webapp && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: AWS_S3_REGION
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_PATH_PUISSANCE
        sync: false
      - key: S3_PATH_ANNUEL
        sync: false
      - key: S3_PATH_MENSUEL
        sync: false
      - key: S3_PATH_PRODUCTION
        sync: false
